# Generated by Django 3.2.9 on 2021-12-05 11:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fis_code', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('distance_points', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('judge_a', models.FloatField(blank=True, null=True)),
                ('judge_b', models.FloatField(blank=True, null=True)),
                ('judge_c', models.FloatField(blank=True, null=True)),
                ('judge_d', models.FloatField(blank=True, null=True)),
                ('judge_e', models.FloatField(blank=True, null=True)),
                ('judge_points', models.FloatField(blank=True, null=True)),
                ('gate', models.IntegerField(blank=True, null=True)),
                ('gate_points', models.FloatField(blank=True, null=True)),
                ('wind', models.FloatField(blank=True, null=True)),
                ('wind_points', models.FloatField(blank=True, null=True)),
                ('total_points', models.FloatField()),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jumper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fis_code', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('born', models.PositiveIntegerField(blank=True, null=True)),
                ('nation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumpers', to='scraper.country')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('team', 'Team'), ('men', 'Men'), ('women', 'Women'), ('other', 'Other')], max_length=50)),
                ('hill_size', models.CharField(max_length=10)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='scraper.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('total_points', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_countries', to='scraper.country')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.race')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('bib', models.PositiveIntegerField(blank=True, null=True)),
                ('total_points', models.FloatField(blank=True, null=True)),
                ('diff', models.FloatField(blank=True, null=True)),
                ('disqualified', models.BooleanField(default=False)),
                ('jump_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_jumps', to='scraper.jump')),
                ('jump_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_jumps', to='scraper.jump')),
                ('jumper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated', to='scraper.jumper')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.race')),
            ],
        ),
    ]
