# Generated by Django 4.0.1 on 2022-01-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_race_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
