# Generated by Django 4.0.1 on 2022-03-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0004_alter_race_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jump",
            name="distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jump",
            name="total_points",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
