# Generated by Django 4.0.1 on 2022-11-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0007_race_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="fis_code",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
