# Generated by Django 4.0.1 on 2022-11-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0008_alter_country_fis_code_alter_country_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folder",
            name="entries",
        ),
        migrations.DeleteModel(
            name="FileMetadata",
        ),
        migrations.DeleteModel(
            name="Folder",
        ),
    ]
